configuration:  
  projectName: CONFIG SERVER PROJECT
server:
  port: 8080
message:
  greeting: Hello from the configuration!
application:
  name: Application Name configured in YAML on config server !
