configuration: 
  projectName: Project Name Web.de DEV
server:
  port: 8080
message:
  greeting: Hello from the configuration!
application:
  name: Application Name configured in YAML on config server !
